version: "3.8"


services:
  app:
    container_name: node_app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./app:/home/app
      - /home/app/node_modules
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
  db:
    build: 
      context: ./mysql
      dockerfile: Dockerfile
    platform: linux/x86_64
    container_name: mysql_db
    image: app_my_sql
    tty: true
    restart: always
    command: --innodb-use-native-aio=0
    volumes:
      - ./mysql/backup:/var/lib/mysql
    networks:
      - app-network
    environment:
      - MYSQL_ROOT_PASSWORD=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_DATABASE=app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      
  nginx:
    container_name: nginx_node_proxy
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: vinihack
    depends_on:
      - app
    ports:
      - 80:80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge